---
language: python
python: "2.7"

install:
  - pip install ansible==1.8.4

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    -e "heroku_toolbelt_users=['travis']"
